# Generated by Django 4.2.3 on 2023-09-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='start',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='log',
            name='end',
        ),
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(default='200', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
