# Generated by Django 4.2.3 on 2023-09-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
        ('inventory', '0002_alter_item_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layout.location', verbose_name='Location'),
        ),
    ]
