# Generated by Django 4.2.3 on 2023-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='x',
            field=models.FloatField(verbose_name='Left'),
        ),
        migrations.AlterField(
            model_name='location',
            name='y',
            field=models.FloatField(verbose_name='Top'),
        ),
    ]
