# Generated by Django 4.2.3 on 2023-09-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_alter_location_x_alter_location_y'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['layout', 'name']},
        ),
    ]
