# Generated by Django 4.2.3 on 2023-10-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layout',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='layout',
            name='order',
            field=models.IntegerField(default=100, verbose_name='Order'),
        ),
    ]
